### ISSUE TITLE
Phase I Preparation Checklist

### ISSUE THREAD

**Issue by aaronjsutton** [aaronjsutton/DarkSpeed-Server#10]
- [x] [Brakeman Security Issues](https://dev.darkspeed.xyz/report/security.html): `0`
- [x] [RuboCop Issues](https://dev.darkspeed.xyz/report/rubocop.html): `0`
- [x] Travis: [![Build Status](https://travis-ci.com/aaronjsutton/DarkSpeed-Server.svg?token=yit2MGjwURDQTA7d5cCk&branch=rewrite)](https://travis-ci.com/aaronjsutton/DarkSpeed-Server)
- [x] [Rake Test Suite Coverage](https://dev.darkspeed.xyz/report/coverage/#_AllFiles): `>70%`
